src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
#[UniqueEntity('title')]
class Property
{
    const HEAT = [
        0 => 'electrique',
        1 => 'gaz',
        2 => 'fioul'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(
        min: 5,
        max: 255,
        minMessage: 'Vous devez saisir au moins {{ limit }} caractères',
        maxMessage: 'Vous devez saisir au plus {{ limit }} caractères',
    )]
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer')]
    #[Assert\Range(min: 10, max: 400, notInRangeMessage: 'Vous devez choisir une valeur entre {{ min }} et {{ max }}',)]
    private $surface;

    #[ORM\Column(type: 'integer')]
    private $rooms;

    #[ORM\Column(type: 'integer')]
    private $bedrooms;

    #[ORM\Column(type: 'integer')]
    private $floor;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'integer')]
    private $heat;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Regex('/^[0-9]{5}$/')]
    private $postal_code;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private $sold = false;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\ManyToMany(targetEntity: Spec::class, inversedBy: 'properties')]
    private $specs;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Images::class, cascade: ['persist', 'remove'])]
    private $images;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->specs = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }


    public function getFormattedPrice(): string
    {
        return  number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Spec>
     */
    public function getSpecs(): Collection
    {
        return $this->specs;
    }

    public function addSpec(Spec $spec): self
    {
        if (!$this->specs->contains($spec)) {
            $this->specs[] = $spec;
            $spec->addProperty($this);
        }

        return $this;
    }

    public function removeSpec(Spec $spec): self
    {
        if ($this->specs->removeElement($spec)) {
            $spec->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProperty($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProperty() === $this) {
                $image->setProperty(null);
            }
        }

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Spec;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\File;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, ['choices' => $this->getChoices()])
            ->add('specs', EntityType::class, [
                'class' => Spec::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
            ->add('images', FileType::class, [
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'mt-2',
                ],
                'constraints' => [new All(array(
                    new Image(array(
                        'minWidth' => 500,
                        'minHeight' => 350,
                        'allowPortrait' => false,
                        'allowPortraitMessage' => 'Les photos doivent être en mode paysage uniquement.',
                        'mimeTypes' => array(
                            'image/jpeg',
                            'image/jpg',
                        ),
                        'mimeTypesMessage' => 'Les photos doivent être au format jpeg ou jpg uniquement.',
                    )),
                    new File(array('maxSize' => 1024000)),
                ))],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;

class PropertyController extends AbstractController
{

	/**
	 * @var PropertyRepository
	 */
	private $repository;

	/**
	 * @var EntityManagerInterface
	 */
	private $em;


	public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
	{
		$this->repository = $repository;
		$this->em = $em;
	}


	/**
	 * @Route("/biens", name="property.index")
	 * @return Response
	 */

	public function index(PaginatorInterface $paginator, Request $request): Response
	{
		$search = new PropertySearch();
		$form = $this->createForm(PropertySearchType::class, $search);

		$form->handleRequest($request);

		$properties = $paginator->paginate(
			$this->repository->findAllVisibleQuery($search),
			$request->query->getInt('page', 1),
			12
		);

		return $this->render('property/index.html.twig', [
			'current_menu' => 'properties',
			'properties' => $properties,
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
	 * @param Property $property
	 * @return ResponseResponse
	 */

	public function show(Property $property, string $slug): Response
	{
		if ($property->getSlug() !== $slug) {
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug()
			], 301);
		}
		return $this->render('property/show.html.twig', [
			'property' => $property,
			'current_menu' => 'properties'
		]);
	}
}

templates/property/_property.html.twig
<div class="card mb-4">
	<a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}" style="text-decoration:none">
		{% if property.images is empty %}
			<img src="{{ asset('/uploads/empty.jpg') | imagine_filter('thumb') }}" class="card-img-top" style="width: 100%; height: auto">
		{% else %}
			{% set photo_bien = property.images|first %}
			<img src="{{ asset('/uploads/' ~ photo_bien.name) | imagine_filter('thumb') }} " class="card-img-top" style="width: 100%; height: auto">
		{% endif %}
		<div class="card-body">
			<h5 class="card-title">
				{{ property.title }}
			</h5>
			<h6 class="card-subtitle mb-2">{{ property.city }}
				({{ property.postalCode }})</h6>
			{% if is_granted('ROLE_ADMIN') %}
				{# Bouton Editer un bien#}
				<a href="{{ path('admin.property.edit', {id: property.id}) }}" class="btn btn-primary" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Editer #
					{{ property.id }}</a>
				{# Bouton Supprimer un bien#}
				<form method="post" action="{{ path('admin.property.delete', {id: property.id}) }}" style="display: inline-block" onsubmit="return confirm('Etes-vous sûr ?')">
					<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
					<button class="btn btn-danger" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Supprimer</button>
				</form>
			{% endif %}
			<p class="card-text">{{property.surface}}m²</p>
			<div class="text-primary" style="font-size:2rem; font-weight: bold;">
				{{ property.formattedPrice }}
				€
			</div>
		</div>
	</a>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Tous nos biens' %}

{% block body%}
	<div class="container mt-4">
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">
				{{ message }}
			</div>
		{% endfor %}
	</div>
	<div class="bg-light p-5 rounded-lg m-3">
		<div class="container">

			{{form_start(form)}}
			<div class="row align-items-end">
				<div class="col-md-2">
					{{ form_row(form.codePostal)}}
				</div>
				<div class="col-md-2">
					{{ form_row(form.minSurface)}}
				</div>
				<div class="col-md-2">
					{{ form_row(form.maxSurface)}}
				</div>
				{% if is_granted('ROLE_ADMIN') %}

					{{ include('admin/property/_id.html.twig')}}
				{% endif %}
			</div>
			<div class="row mt-2 align-items-end">
				<div class="col-md-1">
					{{ form_row(form.nbrRooms)}}
				</div>
				<div class="col-md-2">
					{{ form_row(form.maxPrice)}}
				</div>

			</div>
			<div class="row mt-2 align-items-end">
				<div class="col-md-1">Options:
				</div>
				<div class="col-md-5">
					{{ form_row(form.options)}}
				</div>
			</div>
			<div class="row mt-2">
				<div class="col-md-2">
					<div class="form-group">
						<button class="btn btn-primary">Rechercher</button>
						<a href="{{ path('property.index') }}" class="btn btn-secondary">Annuler</a>
					</div>
				</div>
				<div class="col-md-3 text-primary" style="font-size: 2rem; font-weight: bold;">
					{% if properties.getTotalItemCount < 2 %}
						{% if properties.getTotalItemCount == 0 %}
							Aucun résultat
						{% elseif properties.getTotalItemCount == 1 %}
							{{properties.getTotalItemCount}}
							résultat
						{% endif %}
					{% else %}
						{{properties.getTotalItemCount}}
						résultats
					{% endif %}
				</div>
			</div>
			{{form_end(form)}}

		</div>
	</div>
	<div class="container mt-4">
		<h1>Voir tous nos biens</h1>
		<div class="row">
			{% for property in properties %}
				<div class="col-md-3">
					{% include 'property/_property.html.twig' %}
				</div>
			{% endfor %}
		</div>
		<div class="pagination">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
	<div
		class="bg-light p-5 rounded-lg m-3">
		{#remplace jumbotron #}
		<div class="container">
			<div class="row">
				<div class="col-md-7">
					{% if property.images is empty %}
						Aucune photo n'est publiée.
					{% else %}
						<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
							<div class="carousel-inner">

								{% for image in property.images %}
									<div class="carousel-item {% if loop.first %}active{% endif %}">
										<img src="{{ asset('/uploads/' ~ image.name) | imagine_filter('fixe') }}" class="d-block w-100" alt="Image">
									</div>
								{% endfor %}

							</div>
							<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
								<span class="carousel-control-prev-icon" aria-hidden="true"></span>
								<span class="visually-hidden">Previous</span>
							</button>
							<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
								<span class="carousel-control-next-icon" aria-hidden="true"></span>
								<span class="visually-hidden">Next</span>
							</button>
						</div>
					{% endif %}

				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{ property.surface }}
						m²</h2>
					<h4>{{ property.city }}
						({{ property.postalCode }})</h4>
					<div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary">Contacter l'agence</a>
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4">
		<p>{{ property.description | nl2br }}</p>
		<div class="row">
			<div class="col-md-8">
				<h2>Caracteristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>surface habitable</td>
						<td>{{ property.surface }}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>
							{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<div class="card" style="width: 18rem;">
					<ul class="list-group list-group-flush">
						{% for spec in property.specs %}
							<li class="list-group-item">{{ spec.name }}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}